
namespace HTMLSpitterLib.Css
{
    interface ICssProperties
    {
        string Azimuth { get; set; }
        string BackgroundAttachment { get; set; }
        string BackgroundColor { get; set; }
        string BackgroundImage { get; set; }
        string BackgroundPosition { get; set; }
        string BackgroundRepeat { get; set; }
        string Background { get; set; }
        string BorderCollapse { get; set; }
        string BorderColor { get; set; }
        string BorderSpacing { get; set; }
        string BorderStyle { get; set; }
        string BorderTop { get; set; }
        string BorderTopColor { get; set; }
        string BorderTopStyle { get; set; }
        string BorderTopWidth { get; set; }
        string BorderWidth { get; set; }
        string Border { get; set; }
        string Bottom { get; set; }
        string CaptionSide { get; set; }
        string Clear { get; set; }
        string Clip { get; set; }
        string Color { get; set; }
        string Content { get; set; }
        string CounterIncrement { get; set; }
        string CounterReset { get; set; }
        string CueAfter { get; set; }
        string CueBefore { get; set; }
        string Cue { get; set; }
        string Cursor { get; set; }
        string Direction { get; set; }
        string Display { get; set; }
        string Elevation { get; set; }
        string EmptyCells { get; set; }
        string Float { get; set; }
        string FontFamily { get; set; }
        string FontSize { get; set; }
        string FontStyle { get; set; }
        string FontVariant { get; set; }
        string FontWeight { get; set; }
        string Font { get; set; }
        string Height { get; set; }
        string Left { get; set; }
        string LetterSpacing { get; set; }
        string LineHeight { get; set; }
        string ListStyleImage { get; set; }
        string ListStylePosition { get; set; }
        string ListStyleType { get; set; }
        string ListStyle { get; set; }
        string MarginRight { get; set; }
        string MarginTop { get; set; }
        string Margin { get; set; }
        string MaxHeight { get; set; }
        string MaxWidth { get; set; }
        string MinHeight { get; set; }
        string MinWidth { get; set; }
        string Orphans { get; set; }
        string OutlineColor { get; set; }
        string OutlineStyle { get; set; }
        string OutlineWidth { get; set; }
        string Outline { get; set; }
        string Overflow { get; set; }
        string PaddingTop { get; set; }
        string Padding { get; set; }
        string PageBreakAfter { get; set; }
        string PageBreakBefore { get; set; }
        string PageBreakInside { get; set; }
        string PauseAfter { get; set; }
        string PauseBefore { get; set; }
        string Pause { get; set; }
        string PitchRange { get; set; }
        string Pitch { get; set; }
        string PlayDuring { get; set; }
        string Position { get; set; }
        string Quotes { get; set; }
        string Richness { get; set; }
        string Right { get; set; }
        string SpeakHeader { get; set; }
        string SpeakNumeral { get; set; }
        string SpeakPunctuation { get; set; }
        string Speak { get; set; }
        string SpeechRate { get; set; }
        string Stress { get; set; }
        string TableLayout { get; set; }
        string TextAlign { get; set; }
        string TextDecoration { get; set; }
        string TextIndent { get; set; }
        string TextTransform { get; set; }
        string Top { get; set; }
        string UnicodeBidi { get; set; }
        string VerticalAlign { get; set; }
        string Visibility { get; set; }
        string VoiceFamily { get; set; }
        string Volume { get; set; }
        string WhiteSpace { get; set; }
        string Widows { get; set; }
        string Width { get; set; }
        string WordSpacing { get; set; }
        string ZIndex { get; set; }
    }
}